version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo This is ${ENV}
      - echo ${URL} # defined in BuildProject"
      - NEXT_PUBLIC_DESIGN_URL=${NEXT_PUBLIC_DESIGN_URL}
      - NEXT_PUBLIC_HEALTH_API=${NEXT_PUBLIC_HEALTH_API}
      - NEXT_PUBLIC_API_BASE_URI=${NEXT_PUBLIC_API_BASE_URI}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - npm i next
      - npm run build
      - npm run export

artifacts:
  base-directory: ./out
  files:
    - "**/*"
