export const memberList = [
  {
    id: "1",
    name: "Eason Li",
    profileImg: "/teamProfileImages/eason-li.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/eason-li-dev/",
    githubUrl: "https://github.com/GitHubEason",
    emailAddress: "easonli0216@gmail.com",
  },
  {
    id: "2",
    name: "Beryl Zhou",
    profileImg: "/teamProfileImages/beryl-zhou.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/biyu-zhou-beryl/",
    githubUrl: "https://github.com/Beryl-Zhou",
    emailAddress: "beryl.zhou815@gmail.com",
  },
  {
    id: "3",
    name: "Jenna Wan",
    profileImg: "/teamProfileImages/jenna-wan.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/jenna-wan/",
    githubUrl: "https://github.com/jennawan",
    emailAddress: "jennawan.au@gmail.com",
  },
  {
    id: "4",
    name: "Emily Gong",
    profileImg: "/teamProfileImages/emily-gong.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/emily-gong-dev/",
    githubUrl: "https://github.com/EmilyGong111",
    emailAddress: "emily.gong.dev@gmail.com",
  },
  {
    id: "5",
    name: "Steven Liu",
    profileImg: "/teamProfileImages/steven-liu.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/steven-liu-dev/",
    githubUrl: "https://github.com/stevenliu986",
    emailAddress: "stevenliu986@gmail.com",
  },
  {
    id: "6",
    name: "Korn Zhou",
    profileImg: "/teamProfileImages/korn-zhou.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/korn-zhou/",
    githubUrl: "https://github.com/Kornzk",
    emailAddress: "zk930602@gmail.com",
  },
  {
    id: "7",
    name: "Arina Ke",
    profileImg: "/teamProfileImages/arina-ke.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/arina-ke/",
    githubUrl: "https://github.com/stkwn",
    emailAddress: "arina.ke@gmail.com",
  },
  {
    id: "8",
    name: "John Jiao",
    profileImg: "/teamProfileImages/john-jiao.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/johnjiao/",
    githubUrl: "https://github.com/Jzeva",
    emailAddress: "jzeva1213@gmail.com",
  },
  {
    id: "9",
    name: "Jin Tai",
    profileImg: "/teamProfileImages/jin-tai.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/jin-tai/",
    githubUrl: "https://github.com/Fuchih",
    emailAddress: "t19887348@hotmail.com",
  },
  {
    id: "10",
    name: "Bowen Li",
    profileImg: "/teamProfileImages/bowen-li.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/bowen-bowenli/",
    githubUrl: "https://github.com/BowenLi61",
    emailAddress: "bowenlixxx61@gmail.com",
  },
  {
    id: "11",
    name: "Olivia Xu",
    profileImg: "/teamProfileImages/olivia-xu.jpeg",
    role: "Developer",
    linkedInUrl: "https://www.linkedin.com/in/olivia-xu-devops",
    githubUrl: "",
    emailAddress: "oliviaxu.devops@gmail.com",
  },
  {
    id: "12",
    name: "Kiki Pang",
    profileImg: "/teamProfileImages/kiki-pang.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/qiqi-pang/",
    githubUrl: "https://github.com/ki-ki-316",
    emailAddress: "wwwkiki0316@gmail.com",
  },
  {
    id: "13",
    name: "Sunny Lin",
    profileImg: "/teamProfileImages/sunny-lin.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/sunny-lin-devops/",
    githubUrl: "https://github.com/SunnyLLL",
    emailAddress: "sunnylinql@gmail.com",
  },
  {
    id: "14",
    name: "Kylie Wang",
    profileImg: "/teamProfileImages/kylie-wang.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/qianyu-wang-2020/",
    githubUrl: "",
    emailAddress: "qianyuwang@outlook.com",
  },
  {
    id: "15",
    name: "Sunny Yang",
    profileImg: "/teamProfileImages/sunny-yang.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/sunnyyangyyc/",
    githubUrl: "https://github.com/sunnyyangyyc",
    emailAddress: "6sunnywork@gmail.com",
  },
  {
    id: "16",
    name: "Timmy Lin",
    profileImg: "/teamProfileImages/timmy-lin.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/timmy-lin/",
    githubUrl: "https://github.com/timmyBeef",
    emailAddress: "tim.lin028@gmail.com",
  },
  {
    id: "17",
    name: "Eden Wang",
    profileImg: "/teamProfileImages/eden-wang.jpeg",
    role: "DevOps",
    linkedInUrl: "https://www.linkedin.com/in/eden-wang-86981b241/",
    githubUrl: "",
    emailAddress: "Edenwang0080@gmail.com",
  },
  {
    id: "18",
    name: "Heath Chen",
    profileImg: "/teamProfileImages/heath-chen.jpeg",
    role: "Business Analyst",
    linkedInUrl: "https://www.linkedin.com/in/heath-chen-7611a0150/",
    githubUrl: "",
    emailAddress: "joechen95315@gmail.com",
  },
  {
    id: "19",
    name: "Jie Wei",
    profileImg: "/teamProfileImages/jie-wei.jpeg",
    role: "UI/UX Designer",
    linkedInUrl: "https://www.linkedin.com/in/jie-wei-987b841aa/",
    githubUrl: "",
    emailAddress: "",
  },
];
