import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
// import Link from 'next/link';
import { Links, SizeControls, Counter, CounterControls } from "../components";

// import Layout from "../layouts";
// import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title>Hello world!</Title>

        <SizeControls />
        <Counter />
        <CounterControls />
        <Links />
      </main>

      <footer>this is footer</footer>
    </div>
  );
};

// TODO: move to components if required
const Title = styled.h1`
  color: red;
`;

export default Home;

export const getServerSideProps: GetServerSideProps = async function getServerSideProps({ query }) {
  let start = 0;

  if (query.start && typeof query.start === "string") {
    start = Number(query.start);
  }

  return {
    props: {
      hydrationData: {
        stopwatchStore: {
          start,
        },
      },
    },
  };
};
