name: cc-frontend
on:
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-dependencies
        uses: ./.github/actions/cached-dependencies
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: next-files
          path: .next

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3
  #     - name: Load & cache dependencies
  #       id: cache-dependencies
  #       uses: ./.github/actions/cached-dependencies
  #     - name: Run Unit test
  #       run: npm run test

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-dependencies
        uses: ./.github/actions/cached-dependencies
      - name: Lint code
        run: npm run lint

  deploy-uat:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: next-files
          path: .next
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::245866473499:role/OIDC-Amplify-deployment
          role-session-name: S3Deployment
          aws-region: ap-southeast-2
      - name: Deploy to Amplify
        run: |
          amplify env checkout cc-app-uat
          amplify publish

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: out-files
          path: out
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::245866473499:role/OIDC-Amplify-deployment
          aws-region: ap-southeast-2
      - name: Deploy to Amplify
        run: |
          amplify env checkout cc-app
          amplify publish
